name: Android Release (build via Gradle Action)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7
          arguments: assembleRelease


      - name: Build release APK
        run: gradle assembleRelease --no-daemon

      - name: Upload Release APK (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: CountdownWidgetApp-Release
          path: app/build/outputs/apk/release/app-release.apk

      - name: Create GitHub Release (attach APK)
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
